name: barmaid
description: A trivially simple, API-only self-hosted pub server
version: 0.1.0
repository: https://github.com/gliscowo/barmaid

publish_to: 'http://localhost:8080'

environment:
  sdk: ^3.6.1

dependencies:
  archive: ^4.0.2
  crypto: ^3.0.6
  endec:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  endec_json:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  logging: ^1.3.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  uuid: ^4.5.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.14
  endec_builder:
    hosted: https://pub.wispforest.io
    version: ^0.1.0
  lints: ^5.0.0
  test: ^1.24.0
